Failed experiment: setattr(handle(m_ptr), "__qualname__", qualname);
```
scons: done building targets.
( cd /home/rgrossekunst/forked/pybind11/tests && PYTHONPATH=/home/rgrossekunst/bld/pybind11_gcc/lib /home/rgrossekunst/Venvs/misc/bin/python3 -m pytest -s -vv test_callbacks.py )

AttributeError: attribute '__qualname__' of 'builtin_function_or_method' objects is not writable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rgrossekunst/forked/pybind11/tests/conftest.py", line 25, in <module>
    import pybind11_tests
ImportError: initialization failed
ImportError while loading conftest '/home/rgrossekunst/forked/pybind11/tests/conftest.py'.
conftest.py:25: in <module>
    import pybind11_tests
E   ImportError: initialization failed

ERROR: completed_process.returncode=4
```